// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrJ2PCU7PbzpQbimSY5P_17rH4MTnhX8',
    appId: '1:719361605717:web:560cb137b86ddfe44fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    authDomain: 'libretadulce.firebaseapp.com',
    storageBucket: 'libretadulce.firebasestorage.app',
    measurementId: 'G-34NL99326C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCfp-hFquk-IbpwDTVZasNNlb2t727do',
    appId: '1:719361605717:android:47338acf6351907a4fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    storageBucket: 'libretadulce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWprPZ64rjP6p7w7ediRoSlHS4nQHii4E',
    appId: '1:719361605717:ios:035d3e810c9e51ea4fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    storageBucket: 'libretadulce.firebasestorage.app',
    iosBundleId: 'com.example.libretadulce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWprPZ64rjP6p7w7ediRoSlHS4nQHii4E',
    appId: '1:719361605717:ios:035d3e810c9e51ea4fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    storageBucket: 'libretadulce.firebasestorage.app',
    iosBundleId: 'com.example.libretadulce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrJ2PCU7PbzpQbimSY5P_17rH4MTnhX8',
    appId: '1:719361605717:web:21652d6b002ce8814fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    authDomain: 'libretadulce.firebaseapp.com',
    storageBucket: 'libretadulce.firebasestorage.app',
    measurementId: 'G-661628MG3N',
  );

}