// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCfp-hFquk-IbpwDTVZasNNlb2t727do',
    appId: '1:719361605717:android:47338acf6351907a4fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    storageBucket: 'libretadulce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWprPZ64rjP6p7w7ediRoSlHS4nQHii4E',
    appId: '1:719361605717:ios:035d3e810c9e51ea4fd4dc',
    messagingSenderId: '719361605717',
    projectId: 'libretadulce',
    storageBucket: 'libretadulce.firebasestorage.app',
    iosBundleId: 'com.example.libretadulce',
  );
}
